version: '3.7'
service: 
   django_gunicorn:
   volumes:
     - static:/static
   env_file:
     - .evn   
   build:
     context: .
   ports:
      - "8000:8000"
  nginx:
     build: ./nginx
     volumes:
      - static:/static
     ports:
      - "80:80"       
    depends_on:
      - django_gunicorn
volumes:
   static     
